// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CmdConnect(arg1) {
  return window['go']['core']['App']['CmdConnect'](arg1);
}

export function CmdDisconnect() {
  return window['go']['core']['App']['CmdDisconnect']();
}

export function EvtPayload() {
  return window['go']['core']['App']['EvtPayload']();
}
