// Internal logic constants:
// They are namespaced and the only source of truth, which strengthens the application overall

export const constants = {
    mqttSetupSlice: 'mqttSetupSlice',
    languageSlice: 'languageSlice',
    messagesSlice: 'messagesSlice',
    selectedTopicSlice: 'lastMessageSlice',
    lastMessagesSlice: 'lastMessagesSlice',
    parentNodesSlice: 'parentNodesSlice',
    openedNodesSlice: 'openedNodesSlice',
    customizableSlice: 'customizableSlice',
    cardSlice: 'cardSlice',
    availableLanguages: ['fr', 'en', 'de'],
    host: 'host',
    port: 'port',
    username: 'username',
    password: 'password',
    topic: 'topic',
    reloadEventSlice: 'reloadEventSlice',
    rootID: '-1',
    topicSeparator: '/',
    label: 'label',
    softCard: 'softCard',
    formCard: 'informationCard',
    messagesCard: 'messagesCard',
    treeCard: 'treeCard',
    lastMessageCard: 'lastMessageCard',
    emojiFile: '📄',
    emojiTree: '🌳',
    emojiSunglasses: '🕶️',
    emojiConnection: '📡',
    emojiEnvelop: '📨',
    emojiOkg: '👌',
    emojiSmile: '😀',
    emojiWink: '😉',
    emojiSadge: '☹️',
    xs: 480,
    sm: 768,
    md: 996,
    lg: 1200,
    xl: 1920
};
