// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1) {
  return window['go']['backend']['App']['Connect'](arg1);
}

export function Disconnect() {
  return window['go']['backend']['App']['Disconnect']();
}

export function MQTTPayload() {
  return window['go']['backend']['App']['MQTTPayload']();
}
