// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function CmdConnect(arg1:backend.MQTTClientData):Promise<boolean>;

export function CmdDisconnect():Promise<boolean>;

export function EvtPayload():Promise<backend.Payload>;
