// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function Connect(arg1:backend.MQTTClientData):Promise<boolean>;

export function Disconnect():Promise<boolean>;

export function MQTTPayload():Promise<backend.Payload>;
