// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {core} from '../models';
import {context} from '../models';

export function CmdConnect(arg1:core.MQTTSetup):Promise<boolean>;

export function CmdDisconnect():Promise<boolean>;

export function EvtPayload():Promise<core.MQTTMessage>;

export function Startup(arg1:context.Context):Promise<void>;
