// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Connect(arg1:main.MQTTClientData):Promise<boolean>;

export function Disconnect():Promise<boolean>;

export function MQTTPayload():Promise<main.Payload>;
